### ISSUE TITLE
Open Source Frost API

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/frost-api#222]
I'm creating this ticket to decide exactly when and how to open source Frost API.

I'd like to list and link specific issues we want to address before open sourcing.

I believe it's best to open source BEFORE we hire security professionals. See [Security@ 2017 Panel: Understanding Hacker Motives](https://github.com/poetapp/random/blob/master/Security%40%202017%20Panel:%20Understanding%20Hacker%20Motives.md#conclusions) for reasoning.

@warrenv @wzalazar @geoffturk 

needs poetapp/random#203

### MUST HAVES
* [x] Make sure all tokens & secrets are reconfigured and secure https://github.com/poetapp/frost-api/issues/119
* [x] Reset JWT secret https://github.com/poetapp/frost-api/issues/253
* [x] CORS decision https://github.com/poetapp/frost-api/issues/212

### NICE TO HAVES
* [x] Sort insecure dependencies https://github.com/poetapp/frost-api/issues/194
* [x] Build out unit tests https://github.com/poetapp/frost-api/issues/190
* [x] Add feature toggles https://github.com/poetapp/frost-api/issues/150

### Update 2 March 2019

We've decided to open source Frost API sometime this month.

Overall Frost API needs serious refactoring, which exceeds the amount of time we want to allocate to it right now, so we'll most likely timebox it and release on a fixed date, with as much refactoring done before it as possible.
